services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command:
      - "start-dev"
      - "--import-realm"
      - "--health-enabled=true"
    environment:
      KC_HTTP_PORT: 8181
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8181"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
      - ./docker/keycloak/themes/:/opt/keycloak/themes/
    networks:
      - metahive-network

networks:
  metahive-network:
    driver: bridge

